<?php

$definitions = [
    [
        'label' => 'tree-2',
        'left' => 3,
        'top' => 5,
        'width' => 64,
        'height' => 55,
    ],
    [
        'label' => 'tree-3',
        'left' => 71,
        'top' => 5,
        'width' => 48,
        'height' => 42,
    ],
    [
        'label' => 'tree-4',
        'left' => 123,
        'top' => 5,
        'width' => 36,
        'height' => 31,
    ],
    [
        'label' => 'tree-5',
        'left' => 163,
        'top' => 5,
        'width' => 27,
        'height' => 24,
    ],
    [
        'label' => 'tree-6',
        'left' => 194,
        'top' => 5,
        'width' => 20,
        'height' => 18,
    ],
    [
        'label' => 'tree-7',
        'left' => 218,
        'top' => 5,
        'width' => 15,
        'height' => 14,
    ],
    [
        'label' => 'tree-8',
        'left' => 237,
        'top' => 5,
        'width' => 11,
        'height' => 10,
    ],
    [
        'label' => 'tree-9',
        'left' => 252,
        'top' => 5,
        'width' => 8,
        'height' => 8,
    ],

    // red car centre offset 8

    [
        'label' => 'red-car-centre-1',
        'left' => 3,
        'top' => 1884,
        'width' => 50,
        'height' => 32,
    ],
    [
        'label' => 'red-car-centre-2',
        'left' => 57,
        'top' => 1884,
        'width' => 38,
        'height' => 24,
    ],
    [
        'label' => 'red-car-centre-3',
        'left' => 99,
        'top' => 1884,
        'width' => 28,
        'height' => 18,
    ],
    [
        'label' => 'red-car-centre-4',
        'left' => 131,
        'top' => 1884,
        'width' => 21,
        'height' => 13,
    ],
    [
        'label' => 'red-car-centre-5',
        'left' => 156,
        'top' => 1884,
        'width' => 16,
        'height' => 10,
    ],
    [
        'label' => 'red-car-centre-6',
        'left' => 176,
        'top' => 1884,
        'width' => 12,
        'height' => 8,
    ],
    [
        'label' => 'red-car-centre-7',
        'left' => 192,
        'top' => 1884,
        'width' => 9,
        'height' => 6,
    ],
    [
        'label' => 'red-car-centre-8',
        'left' => 205,
        'top' => 1884,
        'width' => 7,
        'height' => 4,
    ],

    // red car left offset 16

    [
        'label' => 'red-car-left-1',
        'left' => 3,
        'top' => 1919,
        'width' => 63,
        'height' => 32,
    ],
    [
        'label' => 'red-car-left-2',
        'left' => 70,
        'top' => 1919,
        'width' => 47,
        'height' => 24,
    ],
    [
        'label' => 'red-car-left-3',
        'left' => 121,
        'top' => 1919,
        'width' => 35,
        'height' => 18,
    ],
    [
        'label' => 'red-car-left-4',
        'left' => 160,
        'top' => 1919,
        'width' => 27,
        'height' => 14,
    ],
    [
        'label' => 'red-car-left-5',
        'left' => 191,
        'top' => 1919,
        'width' => 20,
        'height' => 10,
    ],
    [
        'label' => 'red-car-left-6',
        'left' => 215,
        'top' => 1919,
        'width' => 15,
        'height' => 8,
    ],
    [
        'label' => 'red-car-left-7',
        'left' => 234,
        'top' => 1919,
        'width' => 11,
        'height' => 6,
    ],
    [
        'label' => 'red-car-left-8',
        'left' => 249,
        'top' => 1919,
        'width' => 7,
        'height' => 4,
    ],

    // red car right offset 24

    [
        'label' => 'red-car-right-1',
        'left' => 3,
        'top' => 1954,
        'width' => 63,
        'height' => 32,
    ],
    [
        'label' => 'red-car-right-2',
        'left' => 70,
        'top' => 1954,
        'width' => 47,
        'height' => 24,
    ],
    [
        'label' => 'red-car-right-3',
        'left' => 121,
        'top' => 1954,
        'width' => 35,
        'height' => 18,
    ],
    [
        'label' => 'red-car-right-4',
        'left' => 160,
        'top' => 1954,
        'width' => 27,
        'height' => 14,
    ],
    [
        'label' => 'red-car-right-5',
        'left' => 191,
        'top' => 1954,
        'width' => 20,
        'height' => 10,
    ],
    [
        'label' => 'red-car-right-6',
        'left' => 215,
        'top' => 1954,
        'width' => 15,
        'height' => 8,
    ],
    [
        'label' => 'red-car-right-7',
        'left' => 234,
        'top' => 1954,
        'width' => 11,
        'height' => 6,
    ],
    [
        'label' => 'red-car-right-8',
        'left' => 249,
        'top' => 1954,
        'width' => 7,
        'height' => 4,
    ],

    // red car intermediates

    [
        'label' => 'red-car-left-intermediate-left-1',
        'left' => 136,
        'top' => 2003,
        'width' => 49,
        'height' => 32,
        'permittedSkews' => [8],
    ],
    [
        'label' => 'red-car-left-intermediate-left-2',
        'left' => 187,
        'top' => 2003,
        'width' => 55,
        'height' => 32,
        'permittedSkews' => [4],
    ],
    [
        'label' => 'red-car-right-intermediate-right-1',
        'left' => 136,
        'top' => 2039,
        'width' => 49,
        'height' => 32,
        'permittedSkews' => [8],
    ],
    [
        'label' => 'red-car-right-intermediate-right-2',
        'left' => 187,
        'top' => 2039,
        'width' => 55,
        'height' => 32,
        'permittedSkews' => [4],
    ],

    // yellow car centre offset 36

    [
        'label' => 'yellow-car-centre-1',
        'left' => 3,
        'top' => 2076,
        'width' => 50,
        'height' => 32,
    ],
    [
        'label' => 'yellow-car-centre-2',
        'left' => 57,
        'top' => 2076,
        'width' => 38,
        'height' => 24,
    ],
    [
        'label' => 'yellow-car-centre-3',
        'left' => 99,
        'top' => 2076,
        'width' => 28,
        'height' => 18,
    ],
    [
        'label' => 'yellow-car-centre-4',
        'left' => 131,
        'top' => 2076,
        'width' => 21,
        'height' => 13,
    ],
    [
        'label' => 'yellow-car-centre-5',
        'left' => 156,
        'top' => 2076,
        'width' => 16,
        'height' => 10,
    ],
    [
        'label' => 'yellow-car-centre-6',
        'left' => 176,
        'top' => 2076,
        'width' => 12,
        'height' => 8,
    ],
    [
        'label' => 'yellow-car-centre-7',
        'left' => 192,
        'top' => 2076,
        'width' => 9,
        'height' => 6,
    ],
    [
        'label' => 'yellow-car-centre-8',
        'left' => 205,
        'top' => 2076,
        'width' => 7,
        'height' => 4,
    ],

    // yellow car left offset 44

    [
        'label' => 'yellow-car-left-1',
        'left' => 3,
        'top' => 2111,
        'width' => 63,
        'height' => 32,
    ],
    [
        'label' => 'yellow-car-left-2',
        'left' => 70,
        'top' => 2111,
        'width' => 47,
        'height' => 24,
    ],
    [
        'label' => 'yellow-car-left-3',
        'left' => 121,
        'top' => 2111,
        'width' => 35,
        'height' => 18,
    ],
    [
        'label' => 'yellow-car-left-4',
        'left' => 160,
        'top' => 2111,
        'width' => 27,
        'height' => 14,
    ],
    [
        'label' => 'yellow-car-left-5',
        'left' => 191,
        'top' => 2111,
        'width' => 20,
        'height' => 10,
    ],
    [
        'label' => 'yellow-car-left-6',
        'left' => 215,
        'top' => 2111,
        'width' => 15,
        'height' => 8,
    ],
    [
        'label' => 'yellow-car-left-7',
        'left' => 234,
        'top' => 2111,
        'width' => 11,
        'height' => 6,
    ],
    [
        'label' => 'yellow-car-left-8',
        'left' => 249,
        'top' => 2111,
        'width' => 7,
        'height' => 4,
    ],

    // yellow car right offset 52

    [
        'label' => 'yellow-car-right-1',
        'left' => 3,
        'top' => 2146,
        'width' => 63,
        'height' => 32,
    ],
    [
        'label' => 'yellow-car-right-2',
        'left' => 70,
        'top' => 2146,
        'width' => 47,
        'height' => 24,
    ],
    [
        'label' => 'yellow-car-right-3',
        'left' => 121,
        'top' => 2146,
        'width' => 35,
        'height' => 18,
    ],
    [
        'label' => 'yellow-car-right-4',
        'left' => 160,
        'top' => 2146,
        'width' => 27,
        'height' => 14,
    ],
    [
        'label' => 'yellow-car-right-5',
        'left' => 191,
        'top' => 2146,
        'width' => 20,
        'height' => 10,
    ],
    [
        'label' => 'yellow-car-right-6',
        'left' => 215,
        'top' => 2146,
        'width' => 15,
        'height' => 8,
    ],
    [
        'label' => 'yellow-car-right-7',
        'left' => 234,
        'top' => 2146,
        'width' => 11,
        'height' => 6,
    ],
    [
        'label' => 'yellow-car-right-8',
        'left' => 249,
        'top' => 2146,
        'width' => 7,
        'height' => 4,
    ],
 
    // blue car centre offset 8

    [
        'label' => 'blue-car-centre-1',
        'left' => 3,
        'top' => 2183,
        'width' => 50,
        'height' => 32,
    ],
    [
        'label' => 'blue-car-centre-2',
        'left' => 57,
        'top' => 2183,
        'width' => 38,
        'height' => 24,
    ],
    [
        'label' => 'blue-car-centre-3',
        'left' => 99,
        'top' => 2183,
        'width' => 28,
        'height' => 18,
    ],
    [
        'label' => 'blue-car-centre-4',
        'left' => 131,
        'top' => 2183,
        'width' => 21,
        'height' => 13,
    ],
    [
        'label' => 'blue-car-centre-5',
        'left' => 156,
        'top' => 2183,
        'width' => 16,
        'height' => 10,
    ],
    [
        'label' => 'blue-car-centre-6',
        'left' => 176,
        'top' => 2183,
        'width' => 12,
        'height' => 8,
    ],
    [
        'label' => 'blue-car-centre-7',
        'left' => 192,
        'top' => 2183,
        'width' => 9,
        'height' => 6,
    ],
    [
        'label' => 'blue-car-centre-8',
        'left' => 205,
        'top' => 2183,
        'width' => 7,
        'height' => 4,
    ],

    // blue car left offset 16

    [
        'label' => 'blue-car-left-1',
        'left' => 3,
        'top' => 2218,
        'width' => 63,
        'height' => 32,
    ],
    [
        'label' => 'blue-car-left-2',
        'left' => 70,
        'top' => 2218,
        'width' => 47,
        'height' => 24,
    ],
    [
        'label' => 'blue-car-left-3',
        'left' => 121,
        'top' => 2218,
        'width' => 35,
        'height' => 18,
    ],
    [
        'label' => 'blue-car-left-4',
        'left' => 160,
        'top' => 2218,
        'width' => 27,
        'height' => 14,
    ],
    [
        'label' => 'blue-car-left-5',
        'left' => 191,
        'top' => 2218,
        'width' => 20,
        'height' => 10,
    ],
    [
        'label' => 'blue-car-left-6',
        'left' => 215,
        'top' => 2218,
        'width' => 15,
        'height' => 8,
    ],
    [
        'label' => 'blue-car-left-7',
        'left' => 234,
        'top' => 2218,
        'width' => 11,
        'height' => 6,
    ],
    [
        'label' => 'blue-car-left-8',
        'left' => 249,
        'top' => 2218,
        'width' => 7,
        'height' => 4,
    ],

    // blue car right offset 24

    [
        'label' => 'blue-car-right-1',
        'left' => 3,
        'top' => 2253,
        'width' => 63,
        'height' => 32,
    ],
    [
        'label' => 'blue-car-right-2',
        'left' => 70,
        'top' => 2253,
        'width' => 47,
        'height' => 24,
    ],
    [
        'label' => 'blue-car-right-3',
        'left' => 121,
        'top' => 2253,
        'width' => 35,
        'height' => 18,
    ],
    [
        'label' => 'blue-car-right-4',
        'left' => 160,
        'top' => 2253,
        'width' => 27,
        'height' => 14,
    ],
    [
        'label' => 'blue-car-right-5',
        'left' => 191,
        'top' => 2253,
        'width' => 20,
        'height' => 10,
    ],
    [
        'label' => 'blue-car-right-6',
        'left' => 215,
        'top' => 2253,
        'width' => 15,
        'height' => 8,
    ],
    [
        'label' => 'blue-car-right-7',
        'left' => 234,
        'top' => 2253,
        'width' => 11,
        'height' => 6,
    ],
    [
        'label' => 'blue-car-right-8',
        'left' => 249,
        'top' => 2253,
        'width' => 7,
        'height' => 4,
    ],

    // michelin offset 56 UPDATED

    [
        'label' => 'michelin-1',
        'left' => 3,
        'top' => 331,
        'width' => 64,
        'height' => 16,
    ],
    [
        'label' => 'michelin-2',
        'left' => 71,
        'top' => 331,
        'width' => 48,
        'height' => 12,
    ],
    [
        'label' => 'michelin-3',
        'left' => 123,
        'top' => 331,
        'width' => 36,
        'height' => 9,
    ],
    [
        'label' => 'michelin-4',
        'left' => 163,
        'top' => 331,
        'width' => 27,
        'height' => 7,
    ],
    [
        'label' => 'michelin-5',
        'left' => 194,
        'top' => 331,
        'width' => 20,
        'height' => 5,
    ],
    [
        'label' => 'michelin-6',
        'left' => 218,
        'top' => 331,
        'width' => 15,
        'height' => 4,
    ],
    [
        'label' => 'michelin-7',
        'left' => 237,
        'top' => 331,
        'width' => 11,
        'height' => 3,
    ],
    [
        'label' => 'michelin-8',
        'left' => 252,
        'top' => 331,
        'width' => 8,
        'height' => 2,
    ],

    // gitanes offset 64 UPDATED

    [
        'label' => 'gitanes-1',
        'left' => 3,
        'top' => 385,
        'width' => 48,
        'height' => 54,
    ],
    [
        'label' => 'gitanes-2',
        'left' => 55,
        'top' => 385,
        'width' => 36,
        'height' => 41,
    ],
    [
        'label' => 'gitanes-3',
        'left' => 95,
        'top' => 385,
        'width' => 27,
        'height' => 30,
    ],
    [
        'label' => 'gitanes-4',
        'left' => 126,
        'top' => 385,
        'width' => 20,
        'height' => 23,
    ],
    [
        'label' => 'gitanes-5',
        'left' => 150,
        'top' => 385,
        'width' => 15,
        'height' => 17,
    ],
    [
        'label' => 'gitanes-6',
        'left' => 169,
        'top' => 385,
        'width' => 11,
        'height' => 12,
    ],
    [
        'label' => 'gitanes-7',
        'left' => 184,
        'top' => 385,
        'width' => 8,
        'height' => 9,
    ],
    [
        'label' => 'gitanes-8',
        'left' => 196,
        'top' => 385,
        'width' => 6,
        'height' => 7,
    ],

    // moto offset 72 UPDATED

    [
        'label' => 'moto-journal-1',
        'left' => 3,
        'top' => 507,
        'width' => 64,
        'height' => 36,
    ],
    [
        'label' => 'moto-journal-2',
        'left' => 71,
        'top' => 507,
        'width' => 48,
        'height' => 27,
    ],
    [
        'label' => 'moto-journal-3',
        'left' => 123,
        'top' => 507,
        'width' => 36,
        'height' => 20,
    ],
    [
        'label' => 'moto-journal-4',
        'left' => 163,
        'top' => 507,
        'width' => 27,
        'height' => 15,
    ],
    [
        'label' => 'moto-journal-5',
        'left' => 194,
        'top' => 507,
        'width' => 20,
        'height' => 11,
    ],
    [
        'label' => 'moto-journal-6',
        'left' => 218,
        'top' => 507,
        'width' => 15,
        'height' => 8,
    ],
    [
        'label' => 'moto-journal-7',
        'left' => 237,
        'top' => 507,
        'width' => 11,
        'height' => 6,
    ],
    [
        'label' => 'moto-journal-8',
        'left' => 252,
        'top' => 507,
        'width' => 8,
        'height' => 5,
    ],

    // total offset 80 UPDATED

    [
        'label' => 'total-1',
        'left' => 3,
        'top' => 569,
        'width' => 48,
        'height' => 15,
    ],
    [
        'label' => 'total-2',
        'left' => 55,
        'top' => 569,
        'width' => 36,
        'height' => 11,
    ],
    [
        'label' => 'total-3',
        'left' => 95,
        'top' => 569,
        'width' => 27,
        'height' => 8,
    ],
    [
        'label' => 'total-4',
        'left' => 126,
        'top' => 569,
        'width' => 20,
        'height' => 6,
    ],
    [
        'label' => 'total-5',
        'left' => 150,
        'top' => 569,
        'width' => 15,
        'height' => 5,
    ],
    [
        'label' => 'total-6',
        'left' => 169,
        'top' => 569,
        'width' => 11,
        'height' => 3,
    ],
    [
        'label' => 'total-7',
        'left' => 184,
        'top' => 569,
        'width' => 8,
        'height' => 3,
    ],
    [
        'label' => 'total-8',
        'left' => 196,
        'top' => 569,
        'width' => 6,
        'height' => 2,
    ],

    // lucas offset 88 UPDATED

    [
        'label' => 'lucas-1',
        'left' => 3,
        'top' => 352,
        'width' => 64,
        'height' => 27,
    ],
    [
        'label' => 'lucas-2',
        'left' => 71,
        'top' => 352,
        'width' => 48,
        'height' => 20,
    ],
    [
        'label' => 'lucas-3',
        'left' => 123,
        'top' => 352,
        'width' => 36,
        'height' => 15,
    ],
    [
        'label' => 'lucas-4',
        'left' => 163,
        'top' => 352,
        'width' => 27,
        'height' => 11,
    ],
    [
        'label' => 'lucas-5',
        'left' => 194,
        'top' => 352,
        'width' => 20,
        'height' => 8,
    ],
    [
        'label' => 'lucas-6',
        'left' => 218,
        'top' => 352,
        'width' => 15,
        'height' => 6,
    ],
    [
        'label' => 'lucas-7',
        'left' => 237,
        'top' => 352,
        'width' => 11,
        'height' => 5,
    ],
    [
        'label' => 'lucas-8',
        'left' => 252,
        'top' => 352,
        'width' => 8,
        'height' => 3,
    ],

    // lamppost offset 96

    [
        'label' => 'lamppost-1',
        'left' => 3,
        'top' => 956,
        'width' => 16,
        'height' => 100,
    ],
    [
        'label' => 'lamppost-2',
        'left' => 23,
        'top' => 956,
        'width' => 12,
        'height' => 75,
    ],
    [
        'label' => 'lamppost-3',
        'left' => 39,
        'top' => 956,
        'width' => 9,
        'height' => 56,
    ],
    [
        'label' => 'lamppost-4',
        'left' => 52,
        'top' => 956,
        'width' => 6,
        'height' => 38,
    ],
    [
        'label' => 'lamppost-5',
        'left' => 62,
        'top' => 956,
        'width' => 5,
        'height' => 31,
    ],
    [
        'label' => 'lamppost-6',
        'left' => 71,
        'top' => 956,
        'width' => 4,
        'height' => 26,
    ],
    [
        'label' => 'lamppost-7',
        'left' => 79,
        'top' => 956,
        'width' => 3,
        'height' => 19,
    ],
    [
        'label' => 'lamppost-8',
        'left' => 86,
        'top' => 956,
        'width' => 2,
        'height' => 13,
    ],

    // left arrow offset 104 UPDATED

    [
        'label' => 'left-arrow-1',
        'left' => 3,
        'top' => 899,
        'width' => 48,
        'height' => 49,
        'permittedSkews' => [],
    ],
    [
        'label' => 'left-arrow-2',
        'left' => 55,
        'top' => 899,
        'width' => 36,
        'height' => 37,
        'permittedSkews' => [],
    ],
    [
        'label' => 'left-arrow-3',
        'left' => 95,
        'top' => 899,
        'width' => 27,
        'height' => 28,
        'permittedSkews' => [],
    ],
    [
        'label' => 'left-arrow-4',
        'left' => 126,
        'top' => 899,
        'width' => 20,
        'height' => 20,
        'permittedSkews' => [],
    ],
    [
        'label' => 'left-arrow-5',
        'left' => 150,
        'top' => 899,
        'width' => 15,
        'height' => 15,
        'permittedSkews' => [],
    ],
    [
        'label' => 'left-arrow-6',
        'left' => 169,
        'top' => 899,
        'width' => 11,
        'height' => 11,
        'permittedSkews' => [],
    ],
    [
        'label' => 'left-arrow-7',
        'left' => 184,
        'top' => 899,
        'width' => 8,
        'height' => 8,
        'permittedSkews' => [],
    ],
    [
        'label' => 'left-arrow-8',
        'left' => 196,
        'top' => 899,
        'width' => 6,
        'height' => 6,
        'permittedSkews' => [],
    ],

    // right arrow offset 112 UPDATED

    [
        'label' => 'right-arrow-1',
        'left' => 3,
        'top' => 449,
        'width' => 48,
        'height' => 49,
    ],
    [
        'label' => 'right-arrow-2',
        'left' => 55,
        'top' => 449,
        'width' => 36,
        'height' => 37,
    ],
    [
        'label' => 'right-arrow-3',
        'left' => 95,
        'top' => 449,
        'width' => 27,
        'height' => 28,
    ],
    [
        'label' => 'right-arrow-4',
        'left' => 126,
        'top' => 449,
        'width' => 20,
        'height' => 20,
    ],
    [
        'label' => 'right-arrow-5',
        'left' => 150,
        'top' => 449,
        'width' => 15,
        'height' => 15,
    ],
    [
        'label' => 'right-arrow-6',
        'left' => 169,
        'top' => 449,
        'width' => 11,
        'height' => 11,
    ],
    [
        'label' => 'right-arrow-7',
        'left' => 184,
        'top' => 449,
        'width' => 8,
        'height' => 8,
    ],
    [
        'label' => 'right-arrow-8',
        'left' => 196,
        'top' => 449,
        'width' => 6,
        'height' => 6,
    ],

    // konami offset 120 UPDATED

    [
        'label' => 'konami-1',
        'left' => 3,
        'top' => 591,
        'width' => 48,
        'height' => 62,
    ],
    [
        'label' => 'konami-2',
        'left' => 55,
        'top' => 591,
        'width' => 36,
        'height' => 47,
    ],
    [
        'label' => 'konami-3',
        'left' => 95,
        'top' => 591,
        'width' => 27,
        'height' => 35,
    ],
    [
        'label' => 'konami-4',
        'left' => 126,
        'top' => 591,
        'width' => 20,
        'height' => 26,
    ],
    [
        'label' => 'konami-5',
        'left' => 150,
        'top' => 591,
        'width' => 15,
        'height' => 19,
    ],
    [
        'label' => 'konami-6',
        'left' => 169,
        'top' => 591,
        'width' => 11,
        'height' => 14,
    ],
    [
        'label' => 'konami-7',
        'left' => 184,
        'top' => 591,
        'width' => 8,
        'height' => 10,
    ],
    [
        'label' => 'konami-8',
        'left' => 196,
        'top' => 591,
        'width' => 6,
        'height' => 7,
    ],

    // bp offset 128 UPDATED

    [
        'label' => 'bp-1',
        'left' => 3,
        'top' => 659,
        'width' => 48,
        'height' => 56,
    ],
    [
        'label' => 'bp-2',
        'left' => 55,
        'top' => 659,
        'width' => 36,
        'height' => 42,
    ],
    [
        'label' => 'bp-3',
        'left' => 95,
        'top' => 659,
        'width' => 27,
        'height' => 32,
    ],
    [
        'label' => 'bp-4',
        'left' => 126,
        'top' => 659,
        'width' => 20,
        'height' => 23,
    ],
    [
        'label' => 'bp-5',
        'left' => 150,
        'top' => 659,
        'width' => 15,
        'height' => 18,
    ],
    [
        'label' => 'bp-6',
        'left' => 169,
        'top' => 659,
        'width' => 11,
        'height' => 13,
    ],
    [
        'label' => 'bp-7',
        'left' => 184,
        'top' => 659,
        'width' => 8,
        'height' => 9,
    ],
    [
        'label' => 'bp-8',
        'left' => 196,
        'top' => 659,
        'width' => 6,
        'height' => 7,
    ],

    // tall tree offset 136 UPDATED

    [
        'label' => 'tall-tree-1',
        'left' => 3,
        'top' => 721,
        'width' => 32,
        'height' => 94,
    ],
    [
        'label' => 'tall-tree-2',
        'left' => 39,
        'top' => 721,
        'width' => 24,
        'height' => 70,
    ],
    [
        'label' => 'tall-tree-3',
        'left' => 67,
        'top' => 721,
        'width' => 18,
        'height' => 53,
    ],
    [
        'label' => 'tall-tree-4',
        'left' => 89,
        'top' => 721,
        'width' => 13,
        'height' => 38,
    ],
    [
        'label' => 'tall-tree-5',
        'left' => 105,
        'top' => 721,
        'width' => 10,
        'height' => 29,
    ],
    [
        'label' => 'tall-tree-6',
        'left' => 120,
        'top' => 721,
        'width' => 7,
        'height' => 21,
    ],
    [
        'label' => 'tall-tree-7',
        'left' => 131,
        'top' => 721,
        'width' => 5,
        'height' => 15,
    ],
    [
        'label' => 'tall-tree-8',
        'left' => 140,
        'top' => 721,
        'width' => 4,
        'height' => 11,
    ],

    // short tree offset 144 UPDATED

    [
        'label' => 'short-tree-1',
        'left' => 3,
        'top' => 820,
        'width' => 48,
        'height' => 72,
    ],
    [
        'label' => 'short-tree-2',
        'left' => 55,
        'top' => 820,
        'width' => 36,
        'height' => 54,
    ],
    [
        'label' => 'short-tree-3',
        'left' => 95,
        'top' => 820,
        'width' => 27,
        'height' => 41,
    ],
    [
        'label' => 'short-tree-4',
        'left' => 126,
        'top' => 820,
        'width' => 20,
        'height' => 30,
    ],
    [
        'label' => 'short-tree-5',
        'left' => 150,
        'top' => 820,
        'width' => 15,
        'height' => 23,
    ],
    [
        'label' => 'short-tree-6',
        'left' => 169,
        'top' => 820,
        'width' => 11,
        'height' => 17,
    ],
    [
        'label' => 'short-tree-7',
        'left' => 184,
        'top' => 820,
        'width' => 8,
        'height' => 12,
    ],
    [
        'label' => 'short-tree-8',
        'left' => 196,
        'top' => 820,
        'width' => 6,
        'height' => 9,
    ],

    // red car flip

    [
        'label' => 'red-car-flip-1',
        'left' => 3,
        'top' => 1724,
        'width' => 105,
        'height' => 41,
        'permittedSkews' => [12],
    ],
    [
        'label' => 'red-car-flip-2',
        'left' => 111,
        'top' => 1724,
        'width' => 108,
        'height' => 37,
        'permittedSkews' => [10],
    ],
    [
        'label' => 'red-car-flip-3',
        'left' => 118,
        'top' => 1766,
        'width' => 111,
        'height' => 51,
        'permittedSkews' => [8],
    ],
    [
        'label' => 'red-car-flip-4',
        'left' => 118,
        'top' => 1830,
        'width' => 108,
        'height' => 37,
        'permittedSkews' => [10],
    ],
    [
        'label' => 'red-car-flip-5',
        'left' => 3,
        'top' => 1828,
        'width' => 105,
        'height' => 39,
        'permittedSkews' => [12],
    ],
    [
        'label' => 'red-car-flip-6',
        'left' => 3,
        'top' => 1766,
        'width' => 112,
        'height' => 59,
        'permittedSkews' => [8],
    ],

    // checkpoint gantry

    [
        'label' => 'checkpoint-gantry-1',
        'left' => 3,
        'top' => 65,
        'width' => 32,
        'height' => 100,
    ],
    [
        'label' => 'checkpoint-gantry-2',
        'left' => 39,
        'top' => 65,
        'width' => 24,
        'height' => 75,
    ],
    [
        'label' => 'checkpoint-gantry-3',
        'left' => 67,
        'top' => 65,
        'width' => 18,
        'height' => 56,
    ],
    [
        'label' => 'checkpoint-gantry-4',
        'left' => 89,
        'top' => 65,
        'width' => 13,
        'height' => 41,
    ],
    [
        'label' => 'checkpoint-gantry-5',
        'left' => 106,
        'top' => 65,
        'width' => 10,
        'height' => 31,
    ],
    [
        'label' => 'checkpoint-gantry-6',
        'left' => 120,
        'top' => 65,
        'width' => 7,
        'height' => 22,
    ],
    [
        'label' => 'checkpoint-gantry-7',
        'left' => 131,
        'top' => 65,
        'width' => 5,
        'height' => 15,
    ],
    [
        'label' => 'checkpoint-gantry-8',
        'left' => 140,
        'top' => 65,
        'width' => 4,
        'height' => 13,
    ],

    // checkpoint top
    [
        'label' => 'checkpoint-top-1',
        'left' => 3,
        'top' => 170,
        'width' => 48,
        'height' => 23,
        'originx' => 16 + 48,
        'originy' => 99,
    ],
    [
        'label' => 'checkpoint-top-2',
        'left' => 55,
        'top' => 170,
        'width' => 36,
        'height' => 17,
        'originx' => 12 + 36,
        'originy' => 74,
    ],
    [
        'label' => 'checkpoint-top-3',
        'left' => 95,
        'top' => 170,
        'width' => 27,
        'height' => 13,
        'originx' => 9 + 27,
        'originy' => 55,
    ],
    [
        'label' => 'checkpoint-top-4',
        'left' => 126,
        'top' => 170,
        'width' => 20,
        'height' => 10,
        'originx' => 6 + 20,
        'originy' => 40,
    ],
    [
        'label' => 'checkpoint-top-5',
        'left' => 150,
        'top' => 170,
        'width' => 15,
        'height' => 7,
        'originx' => 5 + 15,
        'originy' => 30,
    ],
    [
        'label' => 'checkpoint-top-6',
        'left' => 169,
        'top' => 170,
        'width' => 11,
        'height' => 5,
        'originx' => 3 + 11,
        'originy' => 21,
    ],
    [
        'label' => 'checkpoint-top-7',
        'left' => 184,
        'top' => 170,
        'width' => 8,
        'height' => 4,
        'originx' => 2 + 8,
        'originy' => 14,
    ],
    [
        'label' => 'checkpoint-top-8',
        'left' => 196,
        'top' => 170,
        'width' => 6,
        'height' => 3,
        'originx' => 2 + 6,
        'originy' => 12,
    ],

    // game over (202)

    [
        'label' => 'game-over',
        'left' => 24,
        'top' => 2288,
        'width' => 72,
        'height' => 37,
        'permittedSkews' => [12],
    ],

    // get ready (203)

    [
        'label' => 'get-ready',
        'left' => 104,
        'top' => 2288,
        'width' => 90,
        'height' => 37,
        'height' => 37,
        'permittedSkews' => [2],
    ],

    // go! (204)

    [
        'label' => 'go',
        'left' => 206,
        'top' => 2288,
        'width' => 45,
        'height' => 18,
        'permittedSkews' => [10],
    ],

    // speedo (205)

    [
        'label' => 'speedo',
        'left' => 4,
        'top' => 2338,
        'width' => 39,
        'height' => 26,
        'originx' => 0,
        'originy' => 0,
        'permittedSkews' => [1],
    ],

    // speedo digits (206-)

    [
        'label' => 'speedo-0',
        'left' => 53,
        'top' => 2348,
        'width' => 9,
        'height' => 12,
        'originx' => 0,
        'originy' => 0,
        'permittedSkews' => [0, 5, 11],
    ],
    [
        'label' => 'speedo-1',
        'left' => 66,
        'top' => 2348,
        'width' => 9,
        'height' => 12,
        'originx' => 0,
        'originy' => 0,
        'permittedSkews' => [0, 5, 11],
    ],
    [
        'label' => 'speedo-2',
        'left' => 78,
        'top' => 2348,
        'width' => 9,
        'height' => 12,
        'originx' => 0,
        'originy' => 0,
        'permittedSkews' => [0, 5, 11],
    ],
    [
        'label' => 'speedo-3',
        'left' => 91,
        'top' => 2348,
        'width' => 9,
        'height' => 12,
        'originx' => 0,
        'originy' => 0,
        'permittedSkews' => [0, 5, 11],
    ],
    [
        'label' => 'speedo-4',
        'left' => 104,
        'top' => 2348,
        'width' => 9,
        'height' => 12,
        'originx' => 0,
        'originy' => 0,
        'permittedSkews' => [0, 5, 11],
    ],
    [
        'label' => 'speedo-5',
        'left' => 117,
        'top' => 2348,
        'width' => 9,
        'height' => 12,
        'originx' => 0,
        'originy' => 0,
        'permittedSkews' => [0, 5, 11],
    ],
    [
        'label' => 'speedo-6',
        'left' => 130,
        'top' => 2348,
        'width' => 9,
        'height' => 12,
        'originx' => 0,
        'originy' => 0,
        'permittedSkews' => [0, 5, 11],
    ],
    [
        'label' => 'speedo-7',
        'left' => 143,
        'top' => 2348,
        'width' => 9,
        'height' => 12,
        'originx' => 0,
        'originy' => 0,
        'permittedSkews' => [0, 5, 11],
    ],
    [
        'label' => 'speedo-8',
        'left' => 156,
        'top' => 2348,
        'width' => 9,
        'height' => 12,
        'originx' => 0,
        'originy' => 0,
        'permittedSkews' => [0, 5, 11],
    ],
    [
        'label' => 'speedo-9',
        'left' => 169,
        'top' => 2348,
        'width' => 9,
        'height' => 12,
        'originx' => 0,
        'originy' => 0,
        'permittedSkews' => [0, 5, 11],
    ],

    // time extend (216)
    [
        'label' => 'time-extend',
        'left' => 3,
        'top' => 2369,
        'width' => 99,
        'height' => 9,
        'permittedSkews' => [14],
    ],
];

