#ifndef __TRACKSIDE_ITEMS_H
#define __TRACKSIDE_ITEMS_H

#include <inttypes.h>

#define SCENERY_TYPE_ROUND_TREE 0
#define SCENERY_TYPE_MICHELIN 94
#define SCENERY_TYPE_GITANES 130
#define SCENERY_TYPE_MOTO_JOURNAL 112
#define SCENERY_TYPE_TOTAL 121
#define SCENERY_TYPE_LUCAS 130
#define SCENERY_TYPE_LAMPPOST 139
#define SCENERY_TYPE_LEFT_ARROW 148
#define SCENERY_TYPE_RIGHT_ARROW 157
#define SCENERY_TYPE_KONAMI 166
#define SCENERY_TYPE_BP 175
#define SCENERY_TYPE_TALL_TREE 184
#define SCENERY_TYPE_SHORT_TREE 193
#define SCENERY_TYPE_RED_CAR_FLIP 202
#define SCENERY_TYPE_CHECKPOINT_GANTRY 208
#define SCENERY_TYPE_CHECKPOINT_TOP 217
#define SCENERY_TYPE_LEFT_ARROW_YELLOW 241
#define SCENERY_TYPE_RIGHT_ARROW_YELLOW 250

struct TracksideItem {
    uint16_t type;
    int32_t xpos;
    int32_t track_position;
};

extern struct TracksideItem trackside_items[];

#endif
