#ifndef __TRACKSIDE_ITEMS_H
#define __TRACKSIDE_ITEMS_H

#include <inttypes.h>

#define SCENERY_TYPE_ROUND_TREE 0
#define SCENERY_TYPE_MICHELIN 94
#define SCENERY_TYPE_GITANES 130
#define SCENERY_TYPE_MOTO_JOURNAL 112
#define SCENERY_TYPE_TOTAL 121
#define SCENERY_TYPE_LUCAS 130
#define SCENERY_TYPE_LAMPPOST 139
#define SCENERY_TYPE_LEFT_ARROW 156
#define SCENERY_TYPE_RIGHT_ARROW 165
#define SCENERY_TYPE_KONAMI 174
#define SCENERY_TYPE_BP 183
#define SCENERY_TYPE_TALL_TREE 192
#define SCENERY_TYPE_SHORT_TREE 201
#define SCENERY_TYPE_RED_CAR_FLIP 210
#define SCENERY_TYPE_CHECKPOINT_GANTRY 216
#define SCENERY_TYPE_CHECKPOINT_TOP 225
#define SCENERY_TYPE_LEFT_ARROW_YELLOW 249
#define SCENERY_TYPE_RIGHT_ARROW_YELLOW 258

struct TracksideItem {
    uint16_t type;
    int32_t xpos;
    int32_t track_position;
};

extern struct TracksideItem trackside_items[];

#endif
